"""Teacher migration

Revision ID: 6fb907511891
Revises: a38f0718d7fb
Create Date: 2025-12-21 20:30:53.648776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb907511891'
down_revision = 'a38f0718d7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
