"""Initial migration

Revision ID: 76b50d309886
Revises: d8b90c9090d1
Create Date: 2025-12-28 11:24:20.588043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b50d309886'
down_revision = 'd8b90c9090d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('child_password', sa.String(length=255), nullable=False))
        batch_op.create_index(batch_op.f('ix_parent_profiles_child_email'), ['child_email'], unique=True)
        batch_op.drop_column('age')
        batch_op.drop_column('grade')
        batch_op.drop_column('section')
        batch_op.drop_column('city')
        batch_op.drop_column('school')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('section', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('grade', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_parent_profiles_child_email'))
        batch_op.drop_column('child_password')
        batch_op.drop_column('child_email')

    # ### end Alembic commands ###
