"""User migration

Revision ID: 8b9d0cca9464
Revises: 707367660e10
Create Date: 2025-12-21 12:01:15.975897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9d0cca9464'
down_revision = '707367660e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_pic_url', sa.Text(), nullable=True))

    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_pic_url', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.drop_column('profile_pic_url')
        batch_op.drop_column('interests')
        batch_op.drop_column('city')
        batch_op.drop_column('bio')

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('profile_pic_url')
        batch_op.drop_column('interests')
        batch_op.drop_column('city')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
