"""Teacher migration

Revision ID: a38f0718d7fb
Revises: 8b9d0cca9464
Create Date: 2025-12-21 20:03:54.349073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38f0718d7fb'
down_revision = '8b9d0cca9464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handling_classes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(length=255), nullable=True))
        batch_op.drop_column('interests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('school')
        batch_op.drop_column('handling_classes')

    # ### end Alembic commands ###
