"""Migration

Revision ID: d8b90c9090d1
Revises: 180531582a68
Create Date: 2025-12-28 07:13:12.482191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b90c9090d1'
down_revision = '180531582a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('section', sa.String(length=5), nullable=True),
    sa.Column('school', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parent_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_profiles_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_profiles_user_id'))

    op.drop_table('parent_profiles')
    # ### end Alembic commands ###
