"""group-membership

Revision ID: f2a35b0c88be
Revises: 6a6c2c9e4e27
Create Date: 2025-05-17 06:39:33.611823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a35b0c88be'
down_revision = '6a6c2c9e4e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_membership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_membership', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
