"""Add is_recurring and recurring_interval to Expense

Revision ID: f7bf5f32f2c6
Revises: 7cca5e71ef46
Create Date: 2025-05-14 01:42:24.763874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7bf5f32f2c6'
down_revision = '7cca5e71ef46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurring_interval', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('recurring_interval')
        batch_op.drop_column('is_recurring')

    # ### end Alembic commands ###
